name: Deploy to Dreamhost Production

on:
  push:
    branches: 
      - production

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Production Sync
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: contracorners.net/wp-content/themes/${{ secrets.THEME_NAME }}/
          protocol: ftp
          security: loose
          port: 21